//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarathonSkills2020
{
    using System.Collections.Generic;
    
    /// <summary>
    /// Благотворительные организации.
    /// </summary>
    public partial class CharityDB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CharityDB()
        {
            this.Registrations = new HashSet<Registration>();
        }
    
        /// <summary>
        /// ID.
        /// </summary>
        public int CharityId { get; set; }
        /// <summary>
        /// Название благотворительной организации.
        /// </summary>
        public string CharityName { get; set; }
        /// <summary>
        /// Описание благотворительной организации.
        /// </summary>
        public string CharityDescription { get; set; }
        /// <summary>
        /// Логотип благотворительной организации.
        /// </summary>
        public byte[] CharityLogo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registration> Registrations { get; set; }
    }
}
